### ISSUE TITLE
?

### ISSUE THREAD

**Issue by vendethiel** [digitalseraphim/CampaignExtensions#1]
Sorry to ask, but -- what's that, who are you?

**Comment by digitalseraphim** [comment]
Sorry about that, was looking for a friend of mine and you are using a
handle that he usually uses, and so I thought you were him, lol. Once I
added you and looked at your profile, I realized that I was wrong. (It's
homebrew d&d configs for a program called pcgen if you wanted to know).

Sorry again and have a good day!

**Comment by vendethiel** [comment]
It was just a bit surprising :).
